source "https://rubygems.org"
gemspec

gem "jekyll-remote-theme"
gem "jekyll-github-metadata"
gem "jekyll-seo-tag"
gem "jekyll-coffeescript"
gem "jekyll-commonmark-ghpages"
gem "jekyll-github-metadata"
gem "jekyll-paginate"
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-default-layout"
gem "jekyll-titles-from-headings"
gem "jekyll-remote-theme"
